name: spox
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Runtime
  - numpy
  - onnx>=1.13.0
  - python>=3.8

  # Development
  - ipython
  - jinja2
  - jupyterlab
  - make
  - matplotlib
  - nbsphinx
  - numpydoc
  - onnxruntime>=1.13.1
  - pandoc<=2.19.2  # ONNX docstrings in opset generation
  - pip
  - pre-commit
  - pytest-cov
  - pytest>=6
  - setuptools_scm
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
